In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('ohe.csv')
df.head()

,id,name,age,gender,city,education,department,employment_type,marital_status,salary,purchased
0,1,Aarav,25,Male,Mumbai,Bachelor,Sales,Full-time,Single,35000,Yes
1,2,Priya,32,Female,Delhi,Master,Marketing,Full-time,Married,52000,Yes
2,3,Rohan,28,Male,Bangalore,Bachelor,IT,Contract,Single,48000,No
3,4,Sneha,41,Female,Chennai,PhD,Research,Full-time,Married,78000,Yes
4,5,Vikram,35,Male,Mumbai,Master,Finance,Full-time,Married,61000,No

In [3]:
from sklearn.model_selection import train_test_split

In [5]:
X_train,X_test,Y_train,Y_test=train_test_split(df.drop(columns=['id','name','age','education','salary','purchased']),df.iloc[:,-1],test_size=0.2)

In [6]:
X_train

    gender       city department employment_type marital_status
9   Female       Pune   Research       Full-time        Married
2     Male  Bangalore         IT        Contract         Single
13  Female    Chennai         HR        Contract         Single
5   Female       Pune      Sales       Part-time         Single
1   Female      Delhi  Marketing       Full-time        Married
15  Female     Mumbai  Marketing       Full-time         Single
16    Male      Delhi      Sales       Part-time         Single
6     Male      Delhi         IT       Full-time         Single
17  Female  Bangalore   Research       Full-time       Divorced
11  Female      Delhi         IT       Full-time         Single
14    Male       Pune    Finance       Full-time        Married
3   Female    Chennai   Research       Full-time        Married
8     Male    Chennai  Marketing        Contract         Single
18    Male    Chennai         IT       Full-time        Married
7   Female  Bangalore         HR       Full-time        Married
12    Male  Bangalore      Sales       Full-time        Married

In [7]:
from sklearn.preprocessing import OneHotEncoder

In [8]:
ohe=OneHotEncoder(drop='first',sparse_output=False,handle_unknown='ignore')

In [9]:
X_train=ohe.fit_transform(X_train)
X_test=ohe.fit(X_test)

In [10]:
X_train

array([[0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0.],
       [1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0.]])